home_drive/routes/auth.py
from flask import render_template, request, redirect, url_for, Blueprint, flash
import flask_login
from passlib.hash import sha256_crypt
from home_drive.models import User


auth = Blueprint("auth", __name__, template_folder='template', static_folder='static')


@auth.route("/auth/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        if flask_login.current_user.is_authenticated:
            return redirect(url_for("content.home"))

        else:
            return render_template("login.html")

    else:
        try:
            username = request.form["user_name"]
            password = request.form["password"]

            user = User.query.filter_by(username=username).first()

            if user and sha256_crypt.verify(password, user.password):
                flask_login.login_user(user)

                return redirect(url_for("content.home"))

            else:
                flash("Wrong username or password", "error")

                return redirect(url_for("auth.login"))

        except:
            flash("Wrong username or password", "error")

            return redirect(url_for("auth.login"))


@auth.route("/auth/logout", methods=["POST", "GET"])
@flask_login.login_required
def logout():
    flask_login.logout_user()

    return redirect(url_for("content.home"))

home_drive/routes/content.py
from flask import render_template, Blueprint, redirect, url_for, request
from flask import current_app as app
import flask_login
import os
from home_drive.utils import common_utils
from home_drive.decorators import private_space_required


FILES_LOCATION = app.config["FILES_LOCATION"]
MAX_SHARED_FILES_SIZE = app.config["MAX_SHARED_FILES_SIZE"]
PRIVATE_FILES_LOCATION = app.config["PRIVATE_FILES_LOCATION"]
VIDEO_TYPES = app.config["VIDEO_TYPES"]


content = Blueprint("content", __name__, template_folder='template', static_folder='static')


@content.route("/")
def home():
    if flask_login.current_user.is_authenticated:
        files = os.listdir(FILES_LOCATION)

        current_size = f"{str(round(common_utils.get_current_files_size(FILES_LOCATION) / 1000000000, 2))} GB"
        max_size = f"{MAX_SHARED_FILES_SIZE / 1000000000} GB"

        return render_template("index.html", files=files, max_size=max_size, current_size=current_size,
                               video_types=VIDEO_TYPES)

    else:
        return redirect(url_for("auth.login"))


@content.route("/private")
@flask_login.login_required
@private_space_required
def private():
    files = []
    dirs = []

    user_name = flask_login.current_user.username
    common_utils.check_dir(os.path.join(PRIVATE_FILES_LOCATION, user_name))

    objects_path = os.path.join(PRIVATE_FILES_LOCATION, user_name)
    objects = os.listdir(objects_path)

    for obj in objects:
        if os.path.isdir(os.path.join(objects_path, obj)):
            dirs.append(obj)

        else:
            files.append(obj)

    max_private_size = flask_login.current_user.max_files_size

    current_size = f"{str(round(common_utils.get_current_files_size(os.path.join(PRIVATE_FILES_LOCATION, user_name)) / 1000000000, 2))} GB"
    max_size = f"{max_private_size / 1000000000} GB"

    return render_template("private.html", files=files, dirs=dirs, max_size=max_size, current_size=current_size,
                           video_types=VIDEO_TYPES)


@content.route("/upload")
@flask_login.login_required
def upload_view():
    current_user = flask_login.current_user

    if current_user.have_private_space or current_user.can_upload:
        current_size = f"{str(round(common_utils.get_current_files_size(FILES_LOCATION) / 1000000000, 2))} GB"
        max_size = f"{MAX_SHARED_FILES_SIZE / 1000000000} GB"

        return render_template("upload.html", max_size=max_size, current_size=current_size)

    else:
        return redirect(url_for("content.home"))


@content.route("/private/create_dir")
@flask_login.login_required
@private_space_required
def new_directory_view():
    current_size = f"{str(round(common_utils.get_current_files_size(FILES_LOCATION) / 1000000000, 2))} GB"
    max_size = f"{MAX_SHARED_FILES_SIZE / 1000000000} GB"

    return render_template("directory.html", max_size=max_size, current_size=current_size)


@content.route("/private/<dir_name>")
@flask_login.login_required
@private_space_required
def directory_content(dir_name):
    current_user = flask_login.current_user

    objects_path = os.path.join(PRIVATE_FILES_LOCATION, current_user.username)

    if os.path.exists(os.path.join(objects_path, dir_name)):
        files = os.listdir(os.path.join(objects_path, dir_name))

        max_private_size = current_user.max_files_size

        current_size = f"{str(round(common_utils.get_current_files_size(os.path.join(PRIVATE_FILES_LOCATION, current_user.username)) / 1000000000, 2))} GB"
        max_size = f"{max_private_size / 1000000000} GB"

        return render_template("directory_content.html", files=files, max_size=max_size, current_size=current_size,
                               dir_name=dir_name)

    else:
        return redirect(url_for("content.private"))


@content.route("/content/move/<file_name>", methods=["GET", "POST"])
@flask_login.login_required
@private_space_required
def move_file(file_name):
    current_user = flask_login.current_user

    objects_path = os.path.join(PRIVATE_FILES_LOCATION, current_user.username)

    dirs = ["/"]
    objects = os.listdir(objects_path)

    for obj in objects:
        if os.path.isdir(os.path.join(objects_path, obj)):
            dirs.append(obj)

    return render_template("move_file.html", dirs=dirs, file_name=file_name)


@content.route("/content/operations", methods=["GET", "POST"])
@flask_login.login_required
def operations():
    if request.args.get("download_file"):
        return redirect(url_for("files_operations.download", file_name=request.args.get("download_file")))

    elif request.args.get("delete_file"):
        return redirect(url_for("files_operations.delete", file_name=request.args.get("delete_file")))

    elif request.args.get("watch_video"):
        return redirect(url_for("files_operations.watch", file_name=request.args.get("watch_video")))


@content.route("/content/operations_private", methods=["GET", "POST"])
@flask_login.login_required
@private_space_required
def operations_private():
    if request.args.get("download_file"):
        return redirect(url_for("files_operations.download_private", file_name=request.args.get("download_file")))

    elif request.args.get("delete_file"):
        return redirect(url_for("files_operations.delete_private", file_name=request.args.get("delete_file")))

    elif request.args.get("browse_dir"):
        return redirect(url_for("content.directory_content", dir_name=request.args.get("browse_dir")))

    elif request.args.get("move_file"):
        return redirect(url_for("content.move_file", file_name=request.args.get("move_file")))

    elif request.args.get("watch_video"):
        return redirect(url_for("files_operations.watch_private", file_name=request.args.get("watch_video")))

home_drive/routes/errors.py
from flask import render_template, url_for, redirect, Blueprint


errors = Blueprint("errors", __name__, template_folder='template', static_folder='static')


@errors.app_errorhandler(404)
def error_404(error):
    return render_template("error.html", message=error)


@errors.app_errorhandler(500)
def error_500(error):
    return render_template("error.html", message=error)


@errors.app_errorhandler(401)
def error_401(error):
    return redirect(url_for("auth.login"))


@errors.app_errorhandler(405)
def error_405(error):
    return render_template("error.html", message=error)

home_drive/routes/files_operations.py
from flask import render_template, Blueprint, redirect, url_for, request, send_file, make_response, jsonify, flash
import flask_login
from flask import current_app as app
import shutil
import os
from werkzeug.utils import secure_filename
from home_drive.utils import common_utils
from home_drive.decorators import private_space_required


files_operations = Blueprint("files_operations", __name__, template_folder='template', static_folder='static')


FILES_LOCATION = app.config["FILES_LOCATION"]
MAX_SHARED_FILES_SIZE = app.config["MAX_SHARED_FILES_SIZE"]
TMP_LOCATION = app.config["TMP_LOCATION"]
PRIVATE_FILES_LOCATION = app.config["PRIVATE_FILES_LOCATION"]
UPLOAD_CHUNK_SIZE = app.config["UPLOAD_CHUNK_SIZE"]
DOWNLOAD_PREVIEW_FILES_TYPES = app.config["DOWNLOAD_PREVIEW_FILES_TYPES"]


@files_operations.route("/files_operations/download_private/<file_name>", methods=["GET"])
@flask_login.login_required
@private_space_required
def download_private(file_name):
    current_user = flask_login.current_user

    file_name = common_utils.decode_path(file_name)
    as_attachment = True

    file_extension = file_name.split(".")[-1].lower()

    if file_extension.endswith(DOWNLOAD_PREVIEW_FILES_TYPES):
        as_attachment = False

    return send_file(os.path.join(PRIVATE_FILES_LOCATION, current_user.username, file_name),
                     as_attachment=as_attachment, download_name=file_name, max_age=0)


@files_operations.route("/files_operations/watch_private/<file_name>", methods=["GET"])
@flask_login.login_required
@private_space_required
def watch_private(file_name):
    file_name = common_utils.decode_path(file_name)

    return send_file(os.path.join(PRIVATE_FILES_LOCATION, flask_login.current_user.id, file_name),
                     as_attachment=False, download_name=file_name, max_age=0)


@files_operations.route("/files_operations/delete_private/<file_name>", methods=["GET"])
@flask_login.login_required
@private_space_required
def delete_private(file_name):
    current_user = flask_login.current_user

    private_root = os.path.join(PRIVATE_FILES_LOCATION, current_user.username)

    file_name = common_utils.decode_path(file_name)

    if os.path.isdir(os.path.join(private_root, file_name)):
        shutil.rmtree(os.path.join(private_root, file_name))

    else:
        os.remove(os.path.join(private_root, file_name))

    return redirect(url_for("content.private"))


@files_operations.route("/files_operations/download/<file_name>", methods=["GET"])
@flask_login.login_required
def download(file_name):
    as_attachment = True

    file_extension = file_name.split(".")[-1].lower()

    if file_extension.endswith(DOWNLOAD_PREVIEW_FILES_TYPES):
        as_attachment = False

    return send_file(os.path.join(FILES_LOCATION, file_name), as_attachment=as_attachment,
                     download_name=file_name,
                     max_age=0)


@files_operations.route("/files_operations/delete/<file_name>", methods=["GET"])
@flask_login.login_required
def delete(file_name):
    current_user = flask_login.current_user

    if current_user.can_delete_files:
        os.remove(os.path.join(FILES_LOCATION, file_name))

    return redirect(url_for("content.home"))


@files_operations.route("/files_operations/watch/<file_name>", methods=["GET"])
@flask_login.login_required
def watch(file_name):
    file_name = common_utils.decode_path(file_name)

    return send_file(os.path.join(FILES_LOCATION, file_name), as_attachment=False, download_name=file_name,
                     max_age=0)


@files_operations.route("/files_operations/create_dir/process", methods=["POST"])
@flask_login.login_required
@private_space_required
def create_new_directory():
    current_user = flask_login.current_user

    dir_name = request.form["dir_name"]
    dir_name = secure_filename(dir_name)

    if dir_name:
        path_to_user_files = os.path.join(PRIVATE_FILES_LOCATION, current_user.username)

        if dir_name in os.listdir(path_to_user_files):
            flash("Directory exists", "error")

            return redirect(url_for("content.directory_content"))

        else:
            os.mkdir(os.path.join(path_to_user_files, dir_name))

            flash(f"Created directory {dir_name}", "success")

            return redirect(url_for("content.private"))

    else:
        flash("Directory name can't be empty", "error")

        return redirect(url_for("content.directory_content"))


@files_operations.route("/files_operations/upload/finalize/move", methods=["POST", "GET"])
@flask_login.login_required
def move_upload():
    current_user = flask_login.current_user
    can_upload = current_user.can_upload
    have_private_space = current_user.have_private_space

    if can_upload or have_private_space:
        tmp_file_path = os.path.join(TMP_LOCATION, current_user.username, "tmp_file")

        if os.path.exists(tmp_file_path):
            file_name = secure_filename(request.form["file_name"])
            dir_name = secure_filename(request.form["dirs"])
            space = request.form["space"]

            if can_upload and space == "shared":
                if os.path.getsize(tmp_file_path) + common_utils.get_current_files_size(
                        FILES_LOCATION) < MAX_SHARED_FILES_SIZE:

                    if not os.path.exists(os.path.join(FILES_LOCATION, file_name)):
                        shutil.copy2(tmp_file_path, os.path.join(FILES_LOCATION, file_name))

                        os.remove(tmp_file_path)

                        return redirect(url_for("content.home"))

                    else:
                        flash("File already exists, choose different name", "error")

                        return redirect(url_for("files_operations.finalize_upload"))

                else:
                    os.remove(tmp_file_path)

                    return redirect(url_for("content.home"))

            if have_private_space and space == "private":
                if os.path.getsize(tmp_file_path) + common_utils.get_current_files_size(
                        FILES_LOCATION) < MAX_SHARED_FILES_SIZE:

                    files_root_path = os.path.join(PRIVATE_FILES_LOCATION, current_user.username)

                    if dir_name == "/":
                        dest_path = os.path.join(files_root_path, file_name)

                    else:
                        dest_path = os.path.join(files_root_path, dir_name, file_name)

                    if not os.path.exists(dest_path):
                        shutil.copy2(tmp_file_path, dest_path)

                        os.remove(tmp_file_path)

                        return redirect(url_for("content.private"))
                    else:
                        flash("File already exists, choose different name", "error")

                        return redirect(url_for("files_operations.finalize_upload"))

                else:
                    os.remove(tmp_file_path)

                    return redirect(url_for("content.home"))


@files_operations.route("/files_operations/upload/finalize", defaults={"file_name": ""}, methods=["GET"])
@files_operations.route("/files_operations/upload/finalize/<file_name>", methods=["GET"])
@flask_login.login_required
def finalize_upload(file_name):
    current_user = flask_login.current_user
    can_upload = current_user.can_upload
    have_private_space = current_user.have_private_space

    if can_upload or have_private_space:
        objects_root = os.path.join(PRIVATE_FILES_LOCATION, current_user.username)
        objects = os.listdir(objects_root)
        dirs = ["/"]

        for obj in objects:
            if os.path.isdir(os.path.join(objects_root, obj)):
                dirs.append(obj)

        if os.path.exists(os.path.join(TMP_LOCATION, current_user.username, "tmp_file")):
            return render_template("finalize.html", dirs=dirs, file_name=file_name)

        else:
            return redirect(url_for("content.home"))

    else:
        return redirect(url_for("content.home"))


@files_operations.route("/files_operations/upload", methods=["POST"])
@flask_login.login_required
def upload():
    current_user = flask_login.current_user
    can_upload = current_user.can_upload
    have_private_space = current_user.have_private_space

    if can_upload or have_private_space:
        common_utils.check_dir(os.path.join(TMP_LOCATION, current_user.username))

        tmp_file_path = os.path.join(TMP_LOCATION, current_user.username, "tmp_file")

        # Getting filename from POST request header
        # filename = request.headers["X-File-Name"]

        if os.path.exists(tmp_file_path):
            os.remove(tmp_file_path)

        with open(tmp_file_path, "wb") as data:
            while True:
                file_chunk = request.stream.read(UPLOAD_CHUNK_SIZE)

                if len(file_chunk) <= 0:
                    break

                data.write(file_chunk)

        return make_response(jsonify(message="OK"), 200)

    else:
        return make_response(jsonify(message="authorization error"), 401)


@files_operations.route("/files_operations/move/process", methods=["POST"])
@flask_login.login_required
def move_file_process():
    # TODO rework this one
    current_user = flask_login.current_user

    if current_user.have_private_space:
        objects_path = os.path.join(PRIVATE_FILES_LOCATION, current_user.username)

        dirs = ["/"]
        objects = os.listdir(objects_path)

        for obj in objects:
            if os.path.isdir(os.path.join(objects_path, obj)):
                dirs.append(obj)

        if request.form["dirs"]:
            objects_root = os.path.join(PRIVATE_FILES_LOCATION, current_user.username)

            dest_dir = request.form["dirs"]
            file_name = request.form["file_name"]
            file_name = common_utils.decode_path(file_name)

            decoded_name_splited = file_name.split("/")

            if not dest_dir == "/":
                dest_dir = secure_filename(dest_dir)

home_drive/templates/directory.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="navbar">
            <span class="main-title">HomeDrive</span>
            <form action="{{ url_for('auth.logout') }}" method="POST">
                <a href="{{ url_for('content.home') }}">
                    <button type="button" class="upload-button">
                        Home
                    </button>
                </a>
                <button class="logout-button" type="submit">
                    Logout
                </button>
            </form>
        </div>
        <div class="main-container upload-container">
            <div class="upload-container">
                <form action="{{ url_for('files_operations.create_new_directory') }}" method="POST" enctype="multipart/form-data">
                    <p>
                        <input type="text" id="dir_name" name="dir_name" placeholder="directory name">
                    </p>
                    <p>
                        <button id="create_directory_button" class="action-button" type="submit">Create directory</button>
                    </p>
                </form>
            </div>
        </div>
        <div class="footer">
            {{current_size}} / {{max_size}}
        </div>
    </div>
{% endblock %}

home_drive/templates/directory_content.html
{% extends "base.html" %}
{% block content %}
    <div class="action-modal" id="delete-modal">
        <p id="delete-file-name"></p>
        <form method="GET" action="{{ url_for('content.operations_private') }}" enctype="multipart/form-data">
            <button class="modal-delete-button" id="delete-modal-button" name="delete_file" type="submit">Yes</button>
            <button class="modal-close-button" onclick="closeDeleteModal();" type="button">No</button>
        </form>
    </div>
    <div class="container">
        <div class="navbar">
            <span class="main-title">HomeDrive - Private/{{ dir_name }}</span>
            <form action="{{ url_for('auth.logout') }}" method="POST">
                <a href="{{ url_for('content.private') }}">
                    <button type="button" class="upload-button">
                        Private
                    </button>
                </a>
                <button class="logout-button" type="submit">Logout</button>
            </form>
        </div>
        <div class="mode-panel">
            {{dir_name}}
        </div>
        <div class="main-container">
            <form method="GET" action="{{ url_for('content.operations_private') }}" enctype="multipart/form-data">
                {% for file in files %}
                    <div class="item">
                        {{file}}
                        <span class="item-buttons">
                            <button class="move-button" value="{{dir_name}}%2F{{file}}" id="move_file" name="move_file"
                                    type="submit">Move</button>
                            <button id="delete-file-button" class="delete-button" onclick="showDeleteModal(this.value);"
                                    value="{{dir_name}}%2F{{file}}" name="delete_file" type="button">Delete</button>
                            <button class="download-button" value="{{dir_name}}%2F{{file}}"
                                    name="download_file" type="submit">Download</button>
                        </span>
                    </div>
                {% endfor %}
            </form>
        </div>
        <div class="footer">
            {{current_size}} / {{max_size}}
        </div>
    </div>
{% endblock %}

home_drive/templates/error.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="navbar">
            <span class="main-title">HomeDrive - Error</span>
        </div>
        <div class="main-container">
            <p>An error occurred: {{message}}</p>
        </div>
        <div class="footer">
        </div>
    </div>
{% endblock %}

home_drive/templates/finalize.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="navbar">
        <span class="main-title">HomeDrive</span>
        <form action="{{ url_for('auth.logout') }}" method="POST">
            <a href="{{ url_for('content.home') }}">
                <button type="button" class="upload-button">
                    Home
                </button>
            </a>
            <button class="logout-button" type="submit">
                Logout
            </button>
        </form>
    </div>
    <div class="main-container upload-container">
        <div class="upload-container">
            <form action="{{ url_for('files_operations.move_upload') }}" method="POST" enctype="multipart/form-data">
                <p>
                    <input type="text" id="file_name" name="file_name" value="{{ file_name }}">
                </p>
                {% if current_user.can_upload %}
                    <input type="radio" id="shared_radio" name="space" value="shared" checked="checked"
                    onchange="showDirSelect(this.value);">
                    <label for="shared_radio">shared</label><br>
                {% endif %}

                {% if current_user.have_private_space %}
                    <input type="radio" id="private_radio" name="space" value="private" checked="checked"
                    onchange="showDirSelect(this.value);">
                    <label for="private_radio">private</label>
                    <br><br>

                    <label id="dirs_label" for="dirs">Choose a directory to upload file to:</label>
                    <p class="upload_dir_select">
                        <select name="dirs" id="dirs">
                            {% for dir in dirs %}
                                <option value="{{ dir }}" name="dir">{{ dir }}</option>
                            {% endfor %}
                        </select>
                    </p>
                {% endif %}
                <p>
                    <button id="finalize_button" class="action-button" type="submit">Finalize Upload</button>
                </p>
            </form>
        </div>
    </div>
    <div class="footer">
    </div>
</div>
{% endblock %}

home_drive/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="action-modal" id="delete-modal">
        <p id="delete-file-name"></p>
        <form method="GET" action="{{ url_for('content.operations') }}" enctype="multipart/form-data">
            <p class="modal-buttons">
                <button class="modal-delete-button" id="delete-modal-button" name="delete_file" type="submit">Yes</button>
                <button class="modal-close-button" onclick="closeDeleteModal();" type="button">No</button>
            </p>
        </form>
    </div>
    <div class="container">
        <div class="navbar">
            <span class="main-title">HomeDrive</span>
            <form action="{{ url_for('auth.logout') }}" method="POST">
                {% if current_user.can_upload %}
                     <a href="{{ url_for('content.upload_view') }}">
                        <button type="button" class="upload-button">
                            Upload
                        </button>
                     </a>
                {% endif %}
                <button class="logout-button" type="submit">
                    Logout
                </button>
            </form>
        </div>
        <div class="mode-panel">
            <a href="{{ url_for('content.home') }}">Shared</a>
            {% if current_user.have_private_space %}
                <a href="{{ url_for('content.private') }}">Private</a>
            {% endif %}
        </div>
        <div class="main-container">
            <form method="GET" action="{{ url_for('content.operations') }}" enctype="multipart/form-data">
                {%for file in files%}
                    <div class="item">
                        {{file}}
                        <span class="item-buttons">
                            {% if current_user.can_delete_files %}
                                <button id="delete-button" class="delete-button" onclick="showDeleteModal(this.value);"
                                        value="{{file}}" name="delete_file_modal" type="button">Delete</button>
                            {% endif %}
                            <button id="download-button" class="download-button" value="{{file}}"
                                    name="download_file" type="submit" formtarget="_blank">Download</button>
                            {% if file.endswith(video_types) %}
                                <button class="watch-button" value="{{ file }}" name="watch_video" type="submit">Watch</button>
                            {% endif %}
                        </span>
                    </div>
                {%endfor%}
            </form>
        </div>
        <div class="footer">
            {{current_size}} / {{max_size}}
        </div>
    </div>
{% endblock %}

home_drive/templates/move_file.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="navbar">
            <span class="main-title">HomeDrive</span>
            <form action="{{ url_for('auth.logout') }}" method="POST">
                <a href="{{ url_for('content.home') }}">
                    <button type="button" class="upload-button">
                        Home
                    </button>
                </a>
                <button class="logout-button" type="submit">
                    Logout
                </button>
            </form>
        </div>
        <div class="main-container upload-container">
            <div class="upload-container">
                <form action="{{ url_for('files_operations.move_file_process') }}" method="POST" enctype="multipart/form-data">
                    <label id="dirs_label" for="dirs">Choose a directory to move {{ file_name }} to:</label>
                    <p class="upload_dir_select">
                        <select name="dirs" id="dirs">
                            {% for dir in dirs %}
                                <option value="{{ dir }}" name="dir">{{ dir }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <p>
                        <button id="finalize_button" class="finalize-upload-button" type="submit"
                                name="file_name" value="{{ file_name }}">Move file</button>
                    </p>
                </form>
            </div>
        </div>
        <div class="footer">
        </div>
    </div>
{% endblock %}

home_drive/templates/private.html
{% extends "base.html" %}
{% block content %}
    <div class="action-modal" id="delete-modal">
        <p id="delete-file-name"></p>
        <form method="GET" action="{{ url_for('content.operations_private') }}" enctype="multipart/form-data">
            <button class="modal-delete-button" id="delete-modal-button" name="delete_file" type="submit">Yes</button>
            <button class="modal-close-button" onclick="closeDeleteModal();" type="button">No</button>
        </form>
    </div>
    <div class="container">
        <div class="navbar">
            <span class="main-title">HomeDrive - Private</span>
            <form action="{{ url_for('auth.logout') }}" method="POST">
                <a href="{{ url_for('content.new_directory_view') }}">
                    <button type="button" class="upload-button">
                        Create Directory
                    </button>
                </a>
                <a href="{{ url_for('content.upload_view') }}">
                    <button type="button" class="upload-button">
                        Upload
                    </button>
                </a>
                <button class="logout-button" type="submit">
                    Logout
                </button>
            </form>
        </div>
        <div class="mode-panel">
            <a href="{{ url_for('content.home') }}">Shared</a>
            <a href="{{ url_for('content.private') }}">Private</a>
        </div>
        <div class="main-container">
            <form method="GET" action="{{ url_for('content.operations_private') }}" enctype="multipart/form-data">
                {% for dir in dirs %}
                    <div class="item">
                        {{dir}}
                        <span class="item-buttons">
                            <button id="delete-dir-button" class="delete-button" onclick="showDeleteModal(this.value);"
                                        value="{{dir}}" name="delete_file_modal" type="button">Delete</button>
                            <button class="download-button" value="{{dir}}" name="browse_dir" type="submit">Enter</button>
                        </span>
                    </div>
                {% endfor %}
                {% for file in files %}
                    <div class="item">
                        {{file}}
                        <span class="item-buttons">
                            <button class="move-button" value="{{file}}" id="move_file" name="move_file"
                                    type="submit">Move</button>
                            <button id="delete-file-button" class="delete-button" onclick="showDeleteModal(this.value);"
                                    value="{{ file }}" name="delete_file_modal" type="button">Delete</button>
                            <button class="download-button" value="{{ file }}" name="download_file" type="submit" formtarget="_blank">Download</button>
                            {% if file.endswith(video_types) %}
                                <button class="watch-button" value="{{ file }}" name="watch_video" type="submit">Watch</button>
                            {% endif %}
                        </span>
                    </div>
                {% endfor %}
            </form>
        </div>
        <div class="footer">
            {{current_size}} / {{max_size}}
        </div>
    </div>
{% endblock %}